version: '3'
services:
  web:
    build: .
    ports:
      - "5555:5555"
    networks:
      - dev-network
    volumes:
      - ./apps:/apps
    environment:
      - NET_MODE=CN
networks:
  dev-network: 