version: '3'
services:
  redis:
    container_name: redis-server
    image: redis:alpine3.11
    ports: 
      - "16379:6379"
    networks:
      - dev-network
  web:
    container_name: xv
    image: yfsoftcom/xv_search
    ports:
      - "5555:5555"
    networks:
      - dev-network
    environment:
      - PROXY=socks5h://127.0.0.1:7070
      - REDIS_HOST=redis
networks:
  dev-network: 