# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class WorldCupStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetGroupTeams = channel.unary_unary(
        '/worldcup.WorldCup/GetGroupTeams',
        request_serializer=service__pb2.Data.SerializeToString,
        response_deserializer=service__pb2.Data.FromString,
        )


class WorldCupServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetGroupTeams(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WorldCupServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetGroupTeams': grpc.unary_unary_rpc_method_handler(
          servicer.GetGroupTeams,
          request_deserializer=service__pb2.Data.FromString,
          response_serializer=service__pb2.Data.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'worldcup.WorldCup', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
