# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='worldcup',
  syntax='proto3',
  serialized_pb=_b('\n\rservice.proto\x12\x08worldcup\"\x14\n\x04\x44\x61ta\x12\x0c\n\x04text\x18\x01 \x01(\t2=\n\x08WorldCup\x12\x31\n\rGetGroupTeams\x12\x0e.worldcup.Data\x1a\x0e.worldcup.Data\"\x00\x62\x06proto3')
)




_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='worldcup.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='worldcup.Data.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=47,
)

DESCRIPTOR.message_types_by_name['Data'] = _DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:worldcup.Data)
  ))
_sym_db.RegisterMessage(Data)



_WORLDCUP = _descriptor.ServiceDescriptor(
  name='WorldCup',
  full_name='worldcup.WorldCup',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=49,
  serialized_end=110,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetGroupTeams',
    full_name='worldcup.WorldCup.GetGroupTeams',
    index=0,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORLDCUP)

DESCRIPTOR.services_by_name['WorldCup'] = _WORLDCUP

# @@protoc_insertion_point(module_scope)
